#!/bin/bash
set -e
mkdir -p out

src="$1"
[ -f "$src" ] || { echo "usage: $0 <source.tq>"; exit 1; }

echo "Converting to IR..."
./bin/Complier "$src" || exit 1

echo "Converting to obj..."
llc -filetype=obj out.ll -o out/out.o || exit 1

echo "Linking..."
clang out/out.o -o tarkiq-out || exit 1
